# See also:
#   https://github.com/pypa/gh-action-pypi-publish
#   https://docs.pypi.org/trusted-publishers/creating-a-project-through-oidc/
name: Publish release

on:
  release:
    types: [published]

jobs:
  package:
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/varformat
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Create distribution
        run: |
          pip install -r scripts/package-requirements.txt
          python scripts/package.py
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
