# See also:
#   https://github.com/pypa/gh-action-pypi-publish
#   https://docs.pypi.org/trusted-publishers/creating-a-project-through-oidc/
on:
  release:
    types: [published]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Create distribution
        run: |
          pip install -r scripts/package-requirements.txt
          python scripts/package.py
      - name: Save distribution as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: dist
  publish:
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/varformat
    permissions:
      id-token: write
    steps:
      - name: Restore distribution
        uses: actions/download-artifact@v4
        with:
          name: package
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
